import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { formatCents } from "@/lib/money";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function InvoicesPage() {
  const invoices = await prisma.invoice.findMany({ include: { card: true, transactions: { select: { amountCents: true, status: true } }, _count: { select: { transactions: true } } }, orderBy: { referenceMonth: "desc" } });
  return <AppShell><section className="content"><header className="page-title"><div><p className="eyebrow">DOCUMENTOS DE ORIGEM</p><h1>Faturas</h1><p className="intro">Cada fatura importada é a origem dos seus lançamentos e previsões.</p></div><Link className="primary button-link" href="/importar">Importar fatura</Link></header><section className="panel invoice-page-panel"><div className="panel-heading"><div><p className="eyebrow">HISTÓRICO</p><h2>Faturas importadas</h2></div><span className="empty-pill">{invoices.length} documento{invoices.length === 1 ? "" : "s"}</span></div>{invoices.length ? <div className="invoice-history">{invoices.map(invoice => { const total = invoice.totalCents ?? invoice.transactions.filter(item => item.status !== "VOID").reduce((sum, item) => sum + item.amountCents, 0); const referenceLabel = invoice.referenceMonth.toLocaleDateString("pt-BR", { month: "long", year: "numeric" }); const dueLabel = invoice.dueDate?.toLocaleDateString("pt-BR", { month: "long", year: "numeric" }) || "a definir"; return <Link className="invoice-history-row" href={`/lancamentos?mes=${invoice.referenceMonth.getFullYear()}-${String(invoice.referenceMonth.getMonth() + 1).padStart(2, "0")}&cardId=${invoice.cardId}`} key={invoice.id}><span className="card-color" style={{ background: invoice.card.color || "#74cabb" }} /><div><strong>{invoice.card.name} · final {invoice.card.lastFour}</strong><p>Referência: {referenceLabel} · {invoice._count.transactions} lançamentos</p><small>Vencimento: {dueLabel}</small></div><b>{formatCents(total)}</b><span className="invoice-state">Ver lançamentos →</span></Link>; })}</div> : <div className="empty-state compact"><strong>Você ainda não importou nenhuma fatura</strong><span>Comece enviando um CSV ou XLSX do seu cartão.</span><Link className="secondary-button" href="/importar">Importar primeira fatura</Link></div>}</section></section></AppShell>;
}
