import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { CategoryOptions } from "@/components/category-options";
import { formatCents } from "@/lib/money";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function DueInvoicesPage({ searchParams }: { searchParams: Promise<{ mes?: string; cardId?: string; personId?: string; categoryId?: string; status?: string }> }) {
  const filters = await searchParams; const now = new Date();
  const selected = filters.mes?.match(/^\d{4}-\d{2}$/) ? filters.mes : `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const [year, month] = selected.split("-").map(Number);
  const [cards, people, categories] = await Promise.all([prisma.card.findMany({ include: { bank: true }, orderBy: { name: "asc" } }), prisma.person.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.category.findMany({ where: { active: true, parentId: { not: null } }, select: { id: true, name: true, parent: { select: { name: true } } }, orderBy: [{ parent: { name: "asc" } }, { name: "asc" }] })]);
  const transactionWhere = { billingYear: year, billingMonth: month, status: { not: "VOID" as const }, ...(filters.cardId ? { cardId: filters.cardId } : {}), ...(filters.personId ? { personId: filters.personId } : {}), ...(filters.categoryId ? { categoryId: filters.categoryId } : {}) };
  const installmentWhere = { billingYear: year, billingMonth: month, status: { in: ["PROJECTED", "DIVERGENT"] as ("PROJECTED" | "DIVERGENT")[] }, ...(filters.cardId ? { plan: { cardId: filters.cardId } } : {}), ...(filters.personId ? { plan: { personId: filters.personId } } : {}), ...(filters.categoryId ? { plan: { categoryId: filters.categoryId } } : {}) };
  const [confirmed, projected] = await Promise.all([prisma.transaction.findMany({ where: transactionWhere }), prisma.installment.findMany({ where: installmentWhere, include: { plan: true } })]);
  const groups = new Map<string, { card: typeof cards[number]; total: number; confirmed: number; projected: number }>();
  for (const card of cards) if (!filters.cardId || filters.cardId === card.id) groups.set(card.id, { card, total: 0, confirmed: 0, projected: 0 });
  if (filters.status !== "PROJECTED") for (const item of confirmed) { const group = groups.get(item.cardId ?? ""); if (group) { group.total += item.amountCents; group.confirmed += item.amountCents; } }
  if (filters.status !== "CONFIRMED") for (const item of projected) { const group = groups.get(item.plan.cardId); if (group) { group.total += item.amountCents; group.projected += item.amountCents; } }
  const visibleGroups = Array.from(groups.values()).filter(group => group.total !== 0); const total = visibleGroups.reduce((sum, group) => sum + group.total, 0);
  const shift = (delta: number) => { const date = new Date(Date.UTC(year, month - 1 + delta, 1, 12)); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; };
  const monthLabel = new Date(Date.UTC(year, month - 1, 1, 12)).toLocaleDateString("pt-BR", { month: "long", year: "numeric" });
  const query = (value: string) => `/faturas-a-vencer?mes=${value}${filters.cardId ? `&cardId=${filters.cardId}` : ""}${filters.personId ? `&personId=${filters.personId}` : ""}${filters.categoryId ? `&categoryId=${filters.categoryId}` : ""}`;
  return <AppShell><section className="content"><header className="page-title"><div><p className="eyebrow">COMPETÊNCIA DA FATURA</p><h1>Faturas a vencer</h1><p className="intro">Confirmado e previsto para a competência selecionada.</p></div></header><section className="month-switcher panel"><Link href={query(shift(-1))}>‹</Link><div><span>COMPETÊNCIA</span><strong>{monthLabel}</strong><small>Total: {formatCents(total)}</small></div><Link href={query(shift(1))}>›</Link></section><form className="panel filters-panel"><div className="filter-grid"><input type="hidden" name="mes" value={selected} /><label>Cartão<select name="cardId" defaultValue={filters.cardId ?? ""}><option value="">Todos os cartões</option>{cards.map(card => <option value={card.id} key={card.id}>{card.name} · {card.lastFour}</option>)}</select></label><label>Pessoa<select name="personId" defaultValue={filters.personId ?? ""}><option value="">Todas as pessoas</option>{people.map(person => <option value={person.id} key={person.id}>{person.nickname || person.name}</option>)}</select></label><label>Categoria<select name="categoryId" defaultValue={filters.categoryId ?? ""}><option value="">Todas as categorias</option><CategoryOptions categories={categories} /></select></label><label>Status<select name="status" defaultValue={filters.status ?? ""}><option value="">Todos</option><option value="CONFIRMED">Confirmado</option><option value="PROJECTED">Previsto</option></select></label></div><button className="secondary-button" type="submit">Aplicar filtros</button></form><div className="due-invoice-grid">{visibleGroups.map(group => <section className="panel due-card" key={group.card.id}><div className="panel-heading"><div><h2>{group.card.name}</h2><p className="intro">Final {group.card.lastFour}</p></div><strong>{formatCents(group.total)}</strong></div><div className="due-breakdown"><span><i className="confirmed-dot" />Confirmado {formatCents(group.confirmed)}</span><span><i className="projected-dot" />Previsto {formatCents(group.projected)}</span></div><Link className="secondary-link" href={`/faturas-a-vencer/${group.card.id}?mes=${selected}`}>Ver detalhes →</Link></section>)}</div>{!visibleGroups.length && <section className="panel empty-state compact"><strong>Nenhuma cobrança nesta competência</strong><span>As compras importadas e parcelas futuras aparecerão aqui.</span></section>}</section></AppShell>;
}
