import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { prisma } from "@/lib/prisma";
import { createPerson, togglePerson, updatePerson } from "./actions";

export const dynamic = "force-dynamic";

export default async function PeoplePage({ searchParams }: { searchParams: Promise<{ editar?: string }> }) {
  const { editar } = await searchParams;
  const people = await prisma.person.findMany({ orderBy: { name: "asc" } });
  const editing = editar ? people.find(person => person.id === editar) : null;
  return <AppShell><section className="content"><header className="page-title"><div><p className="eyebrow">CADASTRO</p><h1>Pessoas</h1><p className="intro">Defina quem utiliza seus cartões e a quem atribuir cada despesa.</p></div></header><div className="page-grid"><div className="form-stack">{editing ? <form action={updatePerson} className="panel form-panel"><input type="hidden" name="id" value={editing.id} /><h2>Editar pessoa</h2><label>Nome<input name="name" required defaultValue={editing.name} /></label><label>Apelido<input name="nickname" defaultValue={editing.nickname ?? ""} /></label><label>Relacionamento<input name="relationship" defaultValue={editing.relationship ?? ""} /></label><label>Observações<textarea name="notes" defaultValue={editing.notes ?? ""} /></label><div className="button-row"><button className="primary" type="submit">Salvar alterações</button><Link className="secondary-button" href="/pessoas">Cancelar</Link></div></form> : <form action={createPerson} className="panel form-panel"><h2>Nova pessoa</h2><label>Nome<input name="name" required placeholder="Ex.: Maria" /></label><label>Apelido<input name="nickname" placeholder="Ex.: Mãe" /></label><label>Relacionamento<input name="relationship" placeholder="Ex.: Familiar" /></label><label>Observações<textarea name="notes" placeholder="Informações adicionais" /></label><button className="primary" type="submit">Salvar pessoa</button></form>}</div><section className="panel list-panel"><div className="panel-heading"><div><p className="eyebrow">{people.length} CADASTRADA{people.length === 1 ? "" : "S"}</p><h2>Responsáveis</h2></div></div>{people.length ? <div className="data-list">{people.map(person => <article key={person.id}><div className="avatar">{person.name[0]}</div><div className="person-info"><strong>{person.name}</strong><p>{person.nickname ? `Apelido: ${person.nickname} · ` : ""}{person.relationship || "Sem relacionamento informado"}</p></div><span className={`status ${person.status.toLowerCase()}`}>{person.status === "ACTIVE" ? "Ativa" : "Inativa"}</span><div className="row-actions"><Link href={`/pessoas?editar=${person.id}`}>Editar</Link><form action={togglePerson}><input type="hidden" name="id" value={person.id} /><button type="submit">{person.status === "ACTIVE" ? "Inativar" : "Ativar"}</button></form></div></article>)}</div> : <div className="empty-state">Nenhuma pessoa cadastrada ainda.</div>}</section></div></section></AppShell>;
}
