import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { formatCents } from "@/lib/money";
import { prisma } from "@/lib/prisma";
import { bulkUpdateTransactions, updateTransaction } from "./actions";

export const dynamic = "force-dynamic";

const statusLabels = { PENDING: "Pendente", CONFIRMED: "Confirmado", PROJECTED: "Previsto", VOID: "Anulado" };

export default async function TransactionsPage({ searchParams }: { searchParams: Promise<{ mes?: string; cardId?: string; personId?: string; categoryId?: string; status?: string; busca?: string; editar?: string }> }) {
  const filters = await searchParams;
  const now = new Date();
  const selectedMonth = filters.mes?.match(/^\d{4}-\d{2}$/) ? filters.mes : `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const [cards, people, categories] = await Promise.all([
    prisma.card.findMany({ orderBy: { name: "asc" } }),
    prisma.person.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }),
    prisma.category.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
  ]);
  const dateFilter = { gte: new Date(`${selectedMonth}-01T00:00:00`), lt: new Date(`${selectedMonth}-01T00:00:00`) };
  dateFilter.lt.setMonth(dateFilter.lt.getMonth() + 1);
  const where = {
    OR: [{ invoice: { referenceMonth: dateFilter } }, { occurredAt: dateFilter, invoiceId: null }],
    ...(filters.cardId ? { cardId: filters.cardId } : {}),
    ...(filters.personId ? { personId: filters.personId } : {}),
    ...(filters.categoryId ? { categoryId: filters.categoryId } : {}),
    ...(["PENDING", "CONFIRMED", "PROJECTED", "VOID"].includes(filters.status ?? "") ? { status: filters.status as "PENDING" | "CONFIRMED" | "PROJECTED" | "VOID" } : {}),
    ...(filters.busca ? { merchantNormalized: { contains: filters.busca.toUpperCase().replace(/[^A-Z0-9]/g, "") } } : {}),
  };
  const [transactions, editing] = await Promise.all([
    prisma.transaction.findMany({ where, include: { card: true, person: true, category: true, shares: { include: { person: true } }, installment: true, installmentPlan: true }, orderBy: { occurredAt: "desc" }, take: 200 }),
    filters.editar ? prisma.transaction.findUnique({ where: { id: filters.editar }, include: { installment: true, installmentPlan: true } }) : Promise.resolve(null),
  ]);
  const shiftMonth = (delta: number) => { const date = new Date(`${selectedMonth}-01T12:00:00`); date.setMonth(date.getMonth() + delta); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; };
  const monthLabel = new Date(`${selectedMonth}-01T12:00:00`).toLocaleDateString("pt-BR", { month: "long", year: "numeric" });
  const query = (month: string) => { const params = new URLSearchParams(); params.set("mes", month); if (filters.cardId) params.set("cardId", filters.cardId); if (filters.personId) params.set("personId", filters.personId); if (filters.categoryId) params.set("categoryId", filters.categoryId); if (filters.status) params.set("status", filters.status); if (filters.busca) params.set("busca", filters.busca); return `/lancamentos?${params.toString()}`; };
  const monthTotal = transactions.reduce((sum, transaction) => sum + transaction.amountCents, 0);
  return <AppShell><section className="content"><header className="page-title"><div><p className="eyebrow">CONTROLE FINANCEIRO</p><h1>Lançamentos</h1><p className="intro">Tudo que foi reconhecido nas suas faturas.</p></div><Link className="primary button-link" href="/importar">Importar fatura</Link></header>
    <section className="month-switcher panel"><Link href={query(shiftMonth(-1))} aria-label="Mês anterior">‹</Link><div><span>FECHAMENTO DO MÊS</span><strong>{monthLabel}</strong><small>{transactions.length} lançamentos · {formatCents(monthTotal)}</small></div><Link href={query(shiftMonth(1))} aria-label="Próximo mês">›</Link></section>
    <form className="panel filters-panel"><div className="filter-grid"><input type="hidden" name="mes" value={selectedMonth} /><label>Cartão<select name="cardId" defaultValue={filters.cardId ?? ""}><option value="">Todos os cartões</option>{cards.map(card => <option key={card.id} value={card.id}>{card.name} · {card.lastFour}</option>)}</select></label><label>Pessoa<select name="personId" defaultValue={filters.personId ?? ""}><option value="">Todas as pessoas</option>{people.map(person => <option key={person.id} value={person.id}>{person.nickname || person.name}</option>)}</select></label><label>Categoria<select name="categoryId" defaultValue={filters.categoryId ?? ""}><option value="">Todas as categorias</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Status<select name="status" defaultValue={filters.status ?? ""}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="filter-search">Buscar estabelecimento<input name="busca" placeholder="Ex.: Uber" defaultValue={filters.busca ?? ""} /></label></div><button className="secondary-button" type="submit">Aplicar filtros</button></form>
    <div className="page-grid transaction-grid">{editing && <form action={updateTransaction} className="panel form-panel"><input type="hidden" name="id" value={editing.id} /><h2>Editar lançamento</h2><label>Descrição<input name="description" required defaultValue={editing.description} /></label><label>Competência da fatura<input name="competence" type="month" defaultValue={editing.billingYear && editing.billingMonth ? `${editing.billingYear}-${String(editing.billingMonth).padStart(2, "0")}` : ""} /><small>Altera somente este lançamento e mantém a data da compra.</small></label><label>Pessoa responsável<select name="personId" defaultValue={editing.personId ?? ""}><option value="">Sem pessoa</option>{people.map(person => <option key={person.id} value={person.id}>{person.nickname || person.name}</option>)}</select></label><label>Categoria<select name="categoryId" defaultValue={editing.categoryId ?? ""}><option value="">Sem categoria</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Status<select name="status" defaultValue={editing.status}><option value="PENDING">Pendente</option><option value="CONFIRMED">Confirmado</option><option value="PROJECTED">Previsto</option><option value="VOID">Anulado</option></select></label><label>Observações<textarea name="notes" defaultValue={editing.notes ?? ""} /></label>{editing.installmentPlanId && <label>Aplicar alteração<select name="scope" defaultValue="ONLY_THIS"><option value="ONLY_THIS">Apenas esta parcela</option><option value="THIS_AND_FUTURE">Esta e as próximas</option><option value="ALL">Todas as parcelas</option></select></label>}<div className="button-row"><button className="primary" type="submit">Salvar alterações</button><Link className="secondary-button" href={query(selectedMonth)}>Cancelar</Link></div></form>}
      <section className="panel list-panel"><form action={bulkUpdateTransactions}><div className="bulk-launch-toolbar"><strong>Editar selecionados</strong><input name="bulkCompetence" type="month" aria-label="Competência dos selecionados" title="Competência dos selecionados" /><select name="bulkPerson"><option value="">Pessoa...</option>{people.map(person => <option key={person.id} value={person.id}>{person.nickname || person.name}</option>)}<option value="__none__">Remover pessoa</option></select><select name="bulkCategory"><option value="">Categoria...</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}<option value="__none__">Remover categoria</option></select><select name="bulkStatus"><option value="">Status...</option><option value="CONFIRMED">Confirmado</option><option value="PENDING">Pendente</option><option value="VOID">Anulado</option></select><input name="bulkNotes" placeholder="Observação para selecionados" /><button className="secondary-button" type="submit">Aplicar</button></div><div className="panel-heading"><div><p className="eyebrow">REGISTRO DA FATURA</p><h2>Lançamentos do mês</h2></div></div>{transactions.length ? <div className="transaction-list">{transactions.map(transaction => <article key={transaction.id}><input type="checkbox" name="selected" value={transaction.id} /><time>{transaction.occurredAt.toLocaleDateString("pt-BR")}</time><div><strong>{transaction.description}</strong><p>{transaction.shares.length ? transaction.shares.map(share => `${share.person.nickname || share.person.name} ${share.percentageBps / 100}%`).join(" · ") : transaction.person?.nickname || transaction.person?.name || "Revisão necessária"} · {transaction.category?.name || "Sem categoria"} · {statusLabels[transaction.status]}</p></div><div className="transaction-value"><b className={transaction.amountCents < 0 ? "refund-value" : ""}>{formatCents(transaction.amountCents)}</b><span>{transaction.card ? `${transaction.card.name} · ${transaction.card.lastFour}` : "Sem cartão"} {transaction.installment ? `· ${transaction.installment.sequence}/${transaction.installmentPlan?.totalInstallments}` : "· À vista"}</span><Link href={`/lancamentos?editar=${transaction.id}&mes=${selectedMonth}`}>Editar</Link></div></article>)}</div> : <div className="empty-state"><strong>Nenhuma fatura lançada neste mês</strong><span>Importe uma fatura para começar a organizar seus gastos.</span><Link className="secondary-button" href="/importar">Importar fatura</Link></div>}</form></section></div></section></AppShell>;
}
